from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib.units import cm
from datetime import datetime
import io
import tempfile
import os

class ReportGenerator:
    """
    Generates a professional PDF report for Dalil AI experiments.
    """
    
    @staticmethod
    def generate_pdf(filepath, title, dataset_name, model_info, metrics, figures=None):
        """
        filepath: Save location (PDF)
        title: Title of report
        dataset_name: Name of dataset
        model_info: Dict of model params/type
        metrics: Dict of results
        figures: List of matplotlib Figures
        """
        c = canvas.Canvas(filepath, pagesize=A4)
        width, height = A4
        
        # --- Header ---
        c.setFillColorRGB(0.12, 0.12, 0.12) # #1E1E1E
        c.rect(0, height - 3*cm, width, 3*cm, fill=1, stroke=0)
        
        c.setFillColorRGB(1, 1, 1)
        c.setFont("Helvetica-Bold", 24)
        c.drawString(2*cm, height - 2*cm, "Dalil AI Report")
        
        c.setFont("Helvetica", 12)
        c.drawString(width - 7*cm, height - 2*cm, f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M')}")
        
        # --- Content ---
        c.setFillColorRGB(0, 0, 0)
        y = height - 5*cm
        
        # Project Info
        c.setFont("Helvetica-Bold", 16)
        c.drawString(2*cm, y, f"Experiment: {title}")
        y -= 1*cm
        
        c.setFont("Helvetica", 12)
        c.drawString(2*cm, y, f"Dataset: {dataset_name}")
        y -= 0.7*cm
        
        # Model Info
        c.setFont("Helvetica-Bold", 14)
        y -= 1*cm
        c.drawString(2*cm, y, "Model Configuration")
        y -= 0.7*cm
        
        c.setFont("Helvetica", 10)
        for k, v in model_info.items():
            c.drawString(2.5*cm, y, f"{k}: {v}")
            y -= 0.5*cm
            
        # Metrics
        y -= 1*cm
        c.setFont("Helvetica-Bold", 14)
        c.drawString(2*cm, y, "Performance Metrics")
        y -= 0.7*cm
        
        c.setFont("Helvetica", 10)
        for k, v in metrics.items():
            # Highlight interesting metrics
            c.drawString(2.5*cm, y, f"{k}: {v}")
            y -= 0.5*cm
            
        # Figures
        if figures:
            y -= 1*cm
            c.setFont("Helvetica-Bold", 14)
            c.drawString(2*cm, y, "Visualizations")
            y -= 0.5*cm
            
            for fig in figures:
                # Save fig to temp buffer
                img_buf = io.BytesIO()
                fig.savefig(img_buf, format='png', dpi=100, bbox_inches='tight')
                img_buf.seek(0)
                
                # ReportLab requires a file path or PIL ImageReader. 
                # Simplest is writing to temp file for reportlab to read
                with tempfile.NamedTemporaryFile(suffix=".png", delete=False) as tmp:
                    tmp.write(img_buf.getvalue())
                    tmp_name = tmp.name
                
                # Check space
                if y < 10*cm:
                    c.showPage()
                    y = height - 2*cm
                
                # Draw
                # Scale to fit width
                img_w = 16*cm
                img_h = 10*cm # approx
                c.drawImage(tmp_name, 2.5*cm, y - img_h, width=img_w, height=img_h)
                y -= (img_h + 1*cm)
                
                os.unlink(tmp_name)

        # Footer
        c.setFont("Helvetica-Oblique", 8)
        c.drawString(width/2 - 2*cm, 1*cm, "Generated by Dalil AI")
        
        c.save()
